import { Marvel } from "next/font/google";
import "./globals.css";
import Link from "next/link";

import LogoButton from "./LogoButton";

const marvel = Marvel({ weight:'400', subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header() {
  return (
    <header className="py-4">
      <div className="container mx-auto px-4 w-50">
        <Nav />
        <div className="bg-green-700 p-5 shadow-[inset_0_4px_5px_rgba(0,0,0,0.6)] w-544 h-100">
          <p className="text-[64px]">	&gt; Eleanor "Elie" Carlos</p>
        </div>
        <LogoButtons />
      </div>
    </header>
  );
}

function Nav(){
  const linkstyle = "text-[#585858] text-[24px] font-bold bg-[#D9D9D9] py-2 px-3";
  return (
    <nav className="flex items-center py-4">
      <div className="flex-none items-center px-2">
        <Link className={linkstyle} href="/">home</Link>
      </div>
      <div className="flex-none items-center px-2">
        <Link className={linkstyle} href="experience">experience</Link>
      </div>
      <div className="flex-none items-center px-2">
        <Link className={linkstyle} href="side_projects">side projects</Link>
      </div>
      <div className="flex-none items-center px-2">
        <Link className={linkstyle} href="contact_me">contact me</Link>
      </div>
    </nav>
  );
}

function LogoButtons(){
  return (
    <div className="flex items-center py-3">
      <LogoButton src="./LinkedIn_Logo_White.png" alt="LinkedIn Logo" style="bg-[#0072B1] p-2.5 rounded-xl mx-1" link="https://www.linkedin.com/in/eleanor-carlos/" />
      <LogoButton src="./GitHub_Logo_White.svg" alt="GitHub Logo" style="bg-[#2DA44E] p-2.5 rounded-xl mx-1" link="https://github.com/saturdaaaaaaaay"/>
      <LogoButton src="./Itch_io_Logo_White.svg" alt="Itch.io Logo" style="bg-[#FA5C5C] p-2.5 rounded-xl mx-1" link="https://saturdaaaaaaaay.itch.io/" />
    </div>
  );
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={marvel.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
